/**
 * Write every animation clip out as a flat PNG strip.
 *
 *     npm run strips
 *
 * **Why this exists.** The runtime composes strips from the packed atlas inside
 * `stripUrl` (src/ui/sprite.ts), which is right for the game: the atlas is
 * already loaded and a strip costs one canvas. Nothing outside the browser can
 * use that. A design pass rendering a preview from PNGs has to find each clip's
 * frame directory, copy nine files and composite by hand — so seventeen walks
 * existed and three got used, which is not a judgement call, it is friction.
 *
 * The contract here is deliberately IDENTICAL to `stripUrl`'s: one uniform
 * square cell sized to the widest and tallest frame, each frame centred
 * horizontally and BOTTOM-ALIGNED. A consumer of these files and the running
 * game therefore see the same animation, and that is the property worth having
 * — the alternative is a preview that is subtly out of step with the thing it
 * is previewing.
 *
 * `index.json` carries the cell and frame count per strip. Nobody should ever
 * hand-type a sheet width: `actor()`'s own comment in scene.ts records that a
 * wrong one fails SILENTLY, sliding the animation instead of stepping it, which
 * is the worst way for it to fail.
 */
import { writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { encodePng, blankImage, type Image } from './png.ts'
import { readAtlas } from './atlas-read.ts'

const atlas = readAtlas()
type Frame = (typeof atlas.frames)[string]
const OUT = 'art/strips'

// Rebuilt from scratch every run: a stale strip for a clip that has since been
// regenerated is worse than a missing one, because it looks current.
if (existsSync(OUT)) rmSync(OUT, { recursive: true })
mkdirSync(OUT, { recursive: true })

/** Copy a rect out of the atlas into `dst` at (dx, dy). */
function blit(dst: Image, f: Frame, dx: number, dy: number): void {
  const sheet = atlas.imageFor(f)
  for (let y = 0; y < f.h; y++) {
    for (let x = 0; x < f.w; x++) {
      const si = ((f.y + y) * sheet.width + (f.x + x)) * 4
      if (sheet.data[si + 3] === 0) continue
      const tx = dx + x
      const ty = dy + y
      if (tx < 0 || ty < 0 || tx >= dst.width || ty >= dst.height) continue
      const di = (ty * dst.width + tx) * 4
      dst.data[di] = sheet.data[si]
      dst.data[di + 1] = sheet.data[si + 1]
      dst.data[di + 2] = sheet.data[si + 2]
      dst.data[di + 3] = sheet.data[si + 3]
    }
  }
}

const index: Record<string, { cell: number; frames: number; file: string }> = {}
let written = 0
let skipped = 0

for (const [sheetId, clips] of Object.entries(atlas.clipLengths)) {
  const dirs = atlas.dirSets?.[sheetId] ?? atlas.rig.directions
  for (const [clip, frames] of Object.entries(clips)) {
    // A one-frame "clip" is a still. It has a frame key already; a strip of one
    // is a copy with extra steps.
    if (frames < 2) continue
    for (const dir of dirs) {
      const rects: Frame[] = []
      for (let i = 0; i < frames; i++) {
        const f = atlas.frames[`${sheetId}.${clip}.${dir}.${i}`]
        if (!f) break
        rects.push(f)
      }
      // A partial direction is skipped rather than half-written: several v3
      // clips came back with 3 of 8 directions, and a strip missing its tail
      // animates into empty space.
      if (rects.length !== frames) { skipped++; continue }

      let cell = 0
      for (const f of rects) cell = Math.max(cell, f.w, f.h)
      const img = blankImage(cell * frames, cell)
      rects.forEach((f, i) => {
        blit(img, f, Math.round(i * cell + (cell - f.w) / 2), Math.round(cell - f.h))
      })
      const name = `${sheetId}.${clip}.${dir}.png`
      writeFileSync(`${OUT}/${name}`, encodePng(img))
      index[`${sheetId}.${clip}.${dir}`] = { cell, frames, file: name }
      written++
    }
  }
}

writeFileSync(`${OUT}/index.json`, `${JSON.stringify({
  _note:
    'Generated by `npm run strips`. Do not hand-edit. One uniform square cell per '
    + 'frame, frames centred horizontally and BOTTOM-ALIGNED — the identical contract '
    + '`stripUrl` uses at runtime, so a preview built from these and the running game '
    + 'show the same animation. Never hand-type `cell`: a wrong sheet width fails '
    + 'silently by sliding the animation instead of stepping it.',
  strips: index,
}, null, 2)}\n`)

console.log(`${written} strips -> ${OUT}/  (${skipped} skipped for missing directions)`)
