/**
 * Measure every scene sprite's real content box and derive its drawn height.
 *
 *     npm run scale
 *
 * **The bug this fixes.** `art/scene-scale.json` gave buildings a WIDTH and
 * assumed height could be inferred from the canvas. It cannot, because the
 * `ranch.*` group is packed UNTRIMMED — the frame rect is the generation canvas
 * and the art floats inside it with padding. `ranch.farmhouse` is a 256x320
 * canvas holding 194x165 of house, so inferring height from the canvas made a
 * 330-wide house 413 tall instead of 281, and the farmhouse ended up taller
 * than the barn.
 *
 * So the height is MEASURED: scan the alpha channel inside each frame's rect
 * for its true content box, and derive `height = width * (contentH / contentW)`.
 * Generated rather than authored, because a hand-maintained second number for
 * fifty sprites is a number that goes stale the first time one is regenerated.
 *
 * **This honours the art, not the world.** The `tallOverrides` this replaces
 * were derived from real dimensions — a real Aermotor windmill is about 10m
 * tall and 2.5m wide, so 100 wide implied 366 tall. The SPRITE is 68x115, a
 * ratio of 1.7 rather than 4. Drawing it at 366 stretched it. Where the art and
 * the world disagree the art wins, every time: a stretched sprite is a visible
 * defect and a short windmill is a style choice. If we want a taller windmill,
 * that is a regeneration, not a multiplier.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { decodePng } from './png.ts'

interface Frame { x: number; y: number; w: number; h: number }
const atlas = JSON.parse(readFileSync('public/atlas.json', 'utf8')) as {
  frames: Record<string, Frame>
}
const sheet = decodePng(readFileSync('public/atlas.png'))
const scalePath = 'art/scene-scale.json'
const scale = JSON.parse(readFileSync(scalePath, 'utf8')) as Record<string, unknown> & {
  drawAt: Record<string, number>
}

/** The alpha content box inside a frame's rect, or null if the frame is empty. */
function contentBox(f: Frame): { w: number; h: number } | null {
  let x0 = Infinity; let y0 = Infinity; let x1 = -1; let y1 = -1
  for (let y = f.y; y < f.y + f.h; y++) {
    for (let x = f.x; x < f.x + f.w; x++) {
      if (sheet.data[(y * sheet.width + x) * 4 + 3] <= 8) continue
      if (x < x0) x0 = x
      if (x > x1) x1 = x
      if (y < y0) y0 = y
      if (y > y1) y1 = y
    }
  }
  return x1 < 0 ? null : { w: x1 - x0 + 1, h: y1 - y0 + 1 }
}

const height: Record<string, number> = {}
const content: Record<string, string> = {}
const missing: string[] = []

for (const [key, drawW] of Object.entries(scale.drawAt)) {
  // The cast is keyed by sheet id and drawn by HEIGHT already; only the
  // width-keyed entries need a height derived.
  const f = atlas.frames[key] ?? atlas.frames[`${key}.idle.down.0`]
  if (!f) { missing.push(key); continue }
  if (!key.includes('.')) continue
  const box = contentBox(f)
  if (!box) { missing.push(key); continue }
  height[key] = Math.round(drawW * (box.h / box.w))
  content[key] = `${box.w}x${box.h}`
}

const out = { ...scale }
delete (out as Record<string, unknown>).tallOverrides
delete (out as Record<string, unknown>)._tallNote
out._heightNote =
  'GENERATED by `npm run scale`. `drawAt` is a WIDTH for anything with a dotted key '
  + '(buildings, vehicles, props) and a HEIGHT for the cast. `drawAtHeight` is the '
  + 'measured companion for the width-keyed ones, and it must be measured rather than '
  + 'inferred: the ranch group is packed UNTRIMMED, so the frame rect is the generation '
  + 'canvas and the art floats inside it. ranch.farmhouse is a 256x320 canvas holding '
  + '194x165 of house, so inferring height from the canvas made a 330-wide house 413 tall '
  + 'instead of 281 and put it above the barn. `contentBox` records what was measured.'
out._artWinsNote =
  'This replaced a hand-written `tallOverrides` block that was derived from REAL '
  + 'dimensions rather than from the sprites. A real farm windmill is about 10m tall and '
  + '2.5m wide, so 100 wide implied 366 tall; the sprite is 68x115, a ratio of 1.7 and not '
  + '4, and drawing it at 366 stretched it. Where the art and the world disagree, THE ART '
  + 'WINS: a stretched sprite is a visible defect and a short windmill is a style choice. '
  + 'Wanting a taller windmill is a regeneration, not a multiplier.'
out.drawAtHeight = height
out.contentBox = content
writeFileSync(scalePath, `${JSON.stringify(out, null, 2)}\n`)

console.log(`${Object.keys(height).length} heights measured -> ${scalePath}`)
if (missing.length) console.log(`not packed, skipped: ${missing.join(', ')}`)
