/**
 * Measure a pen's GROUND QUAD — the four inside corners of its enclosure.
 *
 *     npm run pens
 *
 * **Why a scene needs this.** A pen is a rectangle on the ground plane drawn in
 * perspective, so "inside the pen" is a quadrilateral and not a box. Without the
 * four corners a scene is guessing where the grass is, which is what put a well
 * inside the chicken run and the hens inside the fence band. With them, an
 * animal's `footY` interpolates between the back and front edges and the near
 * rail's z-index is the front edge.
 *
 * **Detected, not eyeballed.** Every pen is drawn with its interior FILLED —
 * worn dirt, scratched earth, pasture — and that fill is one connected region
 * enclosed by the fence. Flood it from the sprite's centre and the four extreme
 * points of the region ARE the corners, because the quad is diamond-oriented in
 * this projection: topmost is the far corner, bottommost the near one, leftmost
 * and rightmost the sides. No hand-typed numbers, so nothing to go stale when a
 * pen is regenerated.
 *
 * The flood treats a pixel as interior if it is opaque and NOT close to the
 * fence's timber. A fence post crossing the fill would otherwise split the
 * region in two and the near corner would be measured against a rail.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { decodePng } from './png.ts'

interface Frame { x: number; y: number; w: number; h: number }
const atlas = JSON.parse(readFileSync('public/atlas.json', 'utf8')) as {
  frames: Record<string, Frame>
}
const sheet = decodePng(readFileSync('public/atlas.png'))
const OUT = 'art/pen-quads.json'

const PENS = Object.keys(atlas.frames).filter((k) => k.startsWith('pen.'))

interface Quad { far: [number, number]; near: [number, number]; left: [number, number]; right: [number, number] }
const quads: Record<string, Quad & { content: string; footLine: number }> = {}

for (const key of PENS) {
  const f = atlas.frames[key]
  const at = (x: number, y: number): [number, number, number, number] => {
    const i = ((f.y + y) * sheet.width + (f.x + x)) * 4
    return [sheet.data[i], sheet.data[i + 1], sheet.data[i + 2], sheet.data[i + 3]]
  }

  // Seed at the centre, which is always interior on a pen sprite.
  const seed: [number, number] = [Math.floor(f.w / 2), Math.floor(f.h / 2)]
  const [sr, sg, sb, sa] = at(seed[0], seed[1])
  if (sa < 200) { console.log(`${key}: centre is transparent, skipped`); continue }

  // Interior = opaque and within tolerance of the fill colour at the seed. The
  // fills are flat-shaded, so a generous tolerance still excludes the timber.
  const TOL = 64
  const near = (x: number, y: number): boolean => {
    const [r, g, b, a] = at(x, y)
    if (a < 200) return false
    return Math.abs(r - sr) + Math.abs(g - sg) + Math.abs(b - sb) < TOL * 3
  }

  const seen = new Uint8Array(f.w * f.h)
  const stack: number[] = [seed[1] * f.w + seed[0]]
  seen[stack[0]] = 1
  let minX = f.w; let maxX = -1; let minY = f.h; let maxY = -1
  let farX = 0; let nearX = 0; let leftY = 0; let rightY = 0
  while (stack.length) {
    const p = stack.pop()!
    const x = p % f.w
    const y = (p / f.w) | 0
    if (y < minY) { minY = y; farX = x }
    if (y > maxY) { maxY = y; nearX = x }
    if (x < minX) { minX = x; leftY = y }
    if (x > maxX) { maxX = x; rightY = y }
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]] as const) {
      const nx = x + dx
      const ny = y + dy
      if (nx < 0 || ny < 0 || nx >= f.w || ny >= f.h) continue
      const q = ny * f.w + nx
      if (seen[q] || !near(nx, ny)) continue
      seen[q] = 1
      stack.push(q)
    }
  }
  if (maxY < 0) { console.log(`${key}: no interior found, skipped`); continue }

  // The whole sprite's alpha box, for the same reason every other asset
  // publishes one: the padded canvas is not the object.
  let bx0 = f.w; let by0 = f.h; let bx1 = -1; let by1 = -1
  for (let y = 0; y < f.h; y++) {
    for (let x = 0; x < f.w; x++) {
      if (at(x, y)[3] <= 8) continue
      if (x < bx0) bx0 = x
      if (x > bx1) bx1 = x
      if (y < by0) by0 = y
      if (y > by1) by1 = y
    }
  }

  quads[key] = {
    far: [farX, minY],
    near: [nearX, maxY],
    left: [minX, leftY],
    right: [maxX, rightY],
    content: `${bx1 - bx0 + 1}x${by1 - by0 + 1}`,
    // The foot line of the sprite as a whole: where the NEAR fence meets the
    // ground, which is the lowest opaque row.
    footLine: by1,
  }
}

writeFileSync(OUT, `${JSON.stringify({
  _note:
    'GENERATED by `npm run pens`. The four inside corners of each pen\'s ground quad, in '
    + 'SPRITE-LOCAL pixels relative to the frame rect. A pen is a rectangle on the ground '
    + 'plane in perspective, so "inside" is a quadrilateral: `far` is the back corner, '
    + '`near` the front, `left` and `right` the sides. Stand an animal by interpolating its '
    + 'footY between the far and near edges, and give the near rail a z-index of the front '
    + 'edge so an animal at the back draws behind it.',
  _detectionNote:
    'Detected by flooding the interior fill from the sprite centre and taking the four '
    + 'extreme points, which ARE the corners because the quad is diamond-oriented in this '
    + 'projection. Nothing is hand-typed, so nothing goes stale when a pen is regenerated.',
  _footLineNote:
    'footLine is the lowest opaque row of the whole sprite — where the near fence meets the '
    + 'ground. Place the pen by its foot line, not its top.',
  pens: quads,
}, null, 2)}\n`)

console.log(`${Object.keys(quads).length} pen quads -> ${OUT}`)
for (const [k, q] of Object.entries(quads)) {
  console.log(`  ${k}  far${q.far} near${q.near} left${q.left} right${q.right}  content ${q.content}`)
}
if (!PENS.length) console.log('no `pen.*` frames packed yet')
void existsSync
